import socket
import threading
import FreeCAD as App  # type: ignore
import FreeCADGui as Gui  # type: ignore
import time

# Try to import PySide for thread-safe execution via QTimer
try:
    from PySide6 import QtCore  # type: ignore
except ImportError:
    try:
        from PySide2 import QtCore  # type: ignore
    except ImportError:
        QtCore = None

# Build a shared execution namespace so exec()'d scripts have access
# to FreeCAD modules without needing to re-import them each time.
_EXEC_GLOBALS = {
    "__builtins__": __builtins__,
    "App": App,
    "Gui": Gui,
    "FreeCAD": App,
    "FreeCADGui": Gui,
}
try:
    import Part  # type: ignore
    _EXEC_GLOBALS["Part"] = Part
except Exception:
    pass
try:
    import PartDesign  # type: ignore
    _EXEC_GLOBALS["PartDesign"] = PartDesign
except Exception:
    pass
try:
    import ImportGui  # type: ignore
    _EXEC_GLOBALS["ImportGui"] = ImportGui
except Exception:
    pass
try:
    import Mesh  # type: ignore
    _EXEC_GLOBALS["Mesh"] = Mesh
except Exception:
    pass


class ExecutionManager:
    def __init__(self):
        self.queue = []
        if QtCore:
            self.timer = QtCore.QTimer()
            self.timer.timeout.connect(self.process_queue)
            self.timer.start(100) # Check every 100ms
            print("Execution manager using QTimer started.")
        else:
            print("Warning: PySide not found. Falling back to non-thread-safe execution (expect crashes).")

    def process_queue(self):
        while self.queue:
            code, reply_conn = self.queue.pop(0)
            try:
                # Check for internal commands
                if code.startswith("__INTERNAL_CMD__"):
                    import json, os
                    cmd_data = json.loads(code.replace("__INTERNAL_CMD__", ""))
                    if cmd_data.get("action") == "sync_session":
                        self.handle_sync_session(cmd_data)
                    elif cmd_data.get("action") == "export_stl":
                        # Export active document to the requested path
                        path = cmd_data.get("path", "")
                        try:
                            import Mesh as _Mesh  # type: ignore
                            doc = App.ActiveDocument
                            if doc:
                                objs = [o for o in doc.Objects
                                        if hasattr(o, "ViewObject") and o.ViewObject and o.ViewObject.Visibility]
                                if not objs:
                                    objs = doc.Objects
                                _Mesh.export(objs, path)
                                print(f"[Listener] Exported STL → {path}")
                        except Exception as ex:
                            print(f"[Listener] STL export error: {ex}")
                    if reply_conn:
                        try: reply_conn.sendall(b"OK"); reply_conn.close()
                        except: pass
                    continue

                # Normal FreeCAD script execution
                # Safety sanitization: remove potential markdown markers
                if "```" in code:
                    import re
                    match = re.search(r"```(?:python)?\s*\n?(.*?)\n?```", code, re.DOTALL)
                    if match:
                        code = match.group(1).strip()
                    else:
                        lines = code.splitlines()
                        code = "\n".join([l for l in lines if not l.strip().startswith("```")]).strip()

                if not App.ActiveDocument:
                    App.newDocument("Untitled")
                    Gui.updateGui()

                # ── Patch known bad API patterns generated by LLM ──────────
                # App.Matrix4d does not exist
                code = code.replace("App.Matrix4d()", "App.Matrix()")
                code = code.replace("App.Matrix4d", "App.Matrix")

                # App.Matrix has no .translate() method
                # Replace m.translate(x, y, z) with the matrix element approach
                import re as _re
                def _fix_translate(match):
                    args = match.group(1)
                    parts = [a.strip() for a in args.split(",")]
                    if len(parts) == 3:
                        dx, dy, dz = parts
                        var = match.group(0).split(".translate")[0].strip()
                        # Find the variable name from the match context
                        return f"# translate patched\n{var}.A14 = {dx}; {var}.A24 = {dy}; {var}.A34 = {dz}"
                    return match.group(0)
                code = _re.sub(r'(\w+)\.translate\(([^)]+)\)', 
                               lambda m: f"# translate patched\n{m.group(1)}.A14 = {m.group(2).split(',')[0].strip()}; {m.group(1)}.A24 = {m.group(2).split(',')[1].strip() if len(m.group(2).split(','))>1 else '0'}; {m.group(1)}.A34 = {m.group(2).split(',')[2].strip() if len(m.group(2).split(','))>2 else '0'}",
                               code)

                # Inject a helper so STEP-file scripts that try doc.getObject('plane_N') 
                # get a safe no-op wrapper instead of crashing on None.Attribute
                step_guard = (
                    "\n# [Auto-injected] Safe getObject wrapper for STEP parser IDs\n"
                    "_orig_getObject = doc.getObject if doc else None\n"
                    "def _safe_get(name):\n"
                    "    obj = _orig_getObject(name) if _orig_getObject else None\n"
                    "    if obj is None:\n"
                    "        # Parser ID not a real FreeCAD object — return the main shape instead\n"
                    "        candidates = [o for o in doc.Objects if hasattr(o,'Shape') and o.Shape.Solids]\n"
                    "        return candidates[0] if candidates else None\n"
                    "    return obj\n"
                    "doc.getObject = _safe_get\n"
                )
                if "doc.getObject" in code and "shape_obj" not in code:
                    code = step_guard + code


                # Refresh globals with the current active document reference
                _EXEC_GLOBALS["App"] = App
                _EXEC_GLOBALS["Gui"] = Gui
                _EXEC_GLOBALS["doc"] = App.ActiveDocument

                exec(code, _EXEC_GLOBALS)
                Gui.updateGui()
                print(f"Executed {len(code)} bytes of code successfully.")

                if reply_conn:
                    try: reply_conn.sendall(b"OK"); reply_conn.close()
                    except: pass

            except Exception as e:
                import traceback
                traceback.print_exc()
                print(f"Execution error: {e}")
                if reply_conn:
                    try: reply_conn.sendall(b"ERR"); reply_conn.close()
                    except: pass


    def handle_sync_session(self, data):
        import os
        prev_id = data.get("previous_id")
        curr_id = data.get("current_id")
        
        # Use absolute path relative to this script
        script_dir = os.path.dirname(os.path.abspath(__file__))
        exports_dir = os.path.join(script_dir, "exports")
        
        if not os.path.exists(exports_dir):
            os.makedirs(exports_dir)
            
        print(f"Syncing: {prev_id} -> {curr_id}")

        # 1. Save current document as the previous session if it exists
        if prev_id and prev_id != "new":
            try:
                doc = App.ActiveDocument
                if doc:
                    save_path = os.path.join(exports_dir, f"{prev_id}.FCStd")
                    doc.saveAs(save_path)
                    print(f"Saved session {prev_id} to {save_path}")
            except Exception as e:
                print(f"Error saving previous session: {e}")

        # 2. Open or create the current session document
        is_new = (curr_id == "new")
        doc_label = "New Chat" if is_new else f"Chat: {curr_id[:8]}"
        curr_path = os.path.join(exports_dir, f"{curr_id}.FCStd")
        
        try:
            if is_new:
                # Always create a FRESH "New Chat"
                for d in App.listDocuments().values():
                    if d.Label == "New Chat":
                        d.Label = f"Old Chat {int(time.time())}"
                
                doc = App.newDocument()
                doc.Label = "New Chat"
                print("Created fresh project for New Chat")
            else:
                # Check if a document with this label is already open
                found_doc = None
                for d in App.listDocuments().values():
                    if d.Label == doc_label:
                        found_doc = d
                        break
                
                if found_doc:
                    App.setActiveDocument(found_doc.Name)
                    print(f"Switched to existing session: {found_doc.Label}")
                elif os.path.exists(curr_path):
                    # Open existing file
                    App.open(curr_path)
                    new_doc = App.ActiveDocument
                    new_doc.Label = doc_label
                    print(f"Opened session file: {curr_path}")
                else:
                    # Create new document for this session
                    doc = App.newDocument()
                    doc.Label = doc_label
                    print(f"Created new document for session: {doc_label}")
            
            # Force UI update
            Gui.updateGui()
        except Exception as e:
            print(f"Error switching/creating session document: {e}")

    def add_to_queue(self, code, conn=None):
        self.queue.append((code, conn))

# Global manager instance
manager = ExecutionManager()

def run_listener():
    HOST = '127.0.0.1'
    PORT = 6666
    
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        try:
            s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
            s.bind((HOST, PORT))
        except OSError as e:
            if e.errno == 10048:
                print(f"Error: Port {PORT} is already in use. Listener may already be running.")
                return
            else:
                raise e
                
        s.listen()
        print(f"FreeCAD Listener started on {HOST}:{PORT}")
        
        while True:
            conn, addr = s.accept()
            # Keep conn alive — queue processor will reply and we close after
            def _handle(c):
                try:
                    data = c.recv(65536).decode('utf-8')
                    if data:
                        print(f"Received code ({len(data)} bytes). Queuing...")
                        if QtCore:
                            manager.add_to_queue(data, c)
                            # reply will be sent from process_queue
                        else:
                            # Risky fallback — execute immediately
                            exec(data, _EXEC_GLOBALS)
                            c.sendall(b"OK")
                            c.close()
                except Exception as ex:
                    print(f"Handler error: {ex}")
                    try: c.sendall(b"ERR"); c.close()
                    except: pass

            threading.Thread(target=_handle, args=(conn,), daemon=True).start()

# Run in a background thread
threading.Thread(target=run_listener, daemon=True).start()
